name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Install application using make
      run: |
        make install  # Use Makefile to install the dependencies

    - name: Start the application using make and capture PID
      run: |
        make run & echo $! > app.pid  # Start the server and store the process ID in a file
        sleep 60                      # Wait for the server to start up for 10 seconds before running tests

    - name: Stop the application
      run: |
        kill $(cat app.pid)  # Kill the process using the PID stored in the file

    - name: Cleanup
      run: |
        make clean
